### ISSUE TITLE
Failed to load the atom-tizentv package

### ISSUE THREAD

**Issue by ionescu77** [Samsung/atom-tizentv#20]
[Enter steps to reproduce:]

1. Install tizen-atom according to the README
2. Basically download release 1.1.1
3. Restart atom
4. ERROR "Failed to load `atom-tizentv` package"

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [atom-tizentv](https://github.com/Samsung/atom-tizentv) package 1.0.0

### Stack Trace

Failed to load the atom-tizentv package

```
At Cannot find module 'async'
Require stack:
- /Users/myuser/.atom/packages/atom-tizentv-1.1.1/lib/createProject.js
- /Users/myuser/.atom/packages/atom-tizentv-1.1.1/lib/atom-extension-tizensdk.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module 'async'
Require stack:
- /Users/myuser/.atom/packages/atom-tizentv-1.1.1/lib/createProject.js
- /Users/myuser/.atom/packages/atom-tizentv-1.1.1/lib/atom-extension-tizensdk.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/atom-tizentv-1.1.1/lib/createProject.js:4:13)
    at /packages/atom-tizentv-1.1.1/lib/createProject.js:247:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at /packages/atom-tizentv-1.1.1/lib/atom-extension-tizensdk.js:6:21)
    at /packages/atom-tizentv-1.1.1/lib/atom-extension-tizensdk.js:62:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:697035)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122227)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3392023)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3378563
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3377363)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3378136)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382220)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380643
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332606)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-django 0.3.2 
atom-shortcuts 0.0.2 
atom-tizentv 1.0.0 
hyperclick 0.1.5 
keyboard-sounds 0.2.0 
language-log 1.10.1 
minimap 4.39.10 
minimap-split-diff 0.3.7 
monokai 0.27.0 
pane-layout-plus 0.7.4 
split-diff 1.6.1 
sunburst 0.3.0 
sync-settings 5.2.7 
wakatime 10.0.0 
```

**Comment by prozanne** [comment]
Hi

Sorry for inconvenience.
Could you please retry with "atom-tizentv-2"?
https://atom.io/packages/atom-tizentv-2

Thanks!
